name: CI - E2E Tests

on:
  push:
jobs:
  cypress-run:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - name: "Setup Node.js"
        uses: "actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af"
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm install
      - name: "Run Cypress tests"
        run: npx cypress run --spec "cypress/e2e/1-getting-started"
      - name: "Upload mochawesome report"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: cypress/reports
      - name: "Parse Test Results and Send to Slack"
        if: always()
        env:
          AUTH_KEY_SLACK: ${{ secrets.AUTH_KEY_SLACK }}
        run: |
          report="cypress/reports/index.json"
          total=$(jq '.stats.tests' $report)
          failed=$(jq '.stats.failures' $report)
          passed=$(jq '.stats.passed' $report)
          pending=$(jq '.stats.pending' $report)
          skipped=$(jq '.stats.skipped' $report)
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [ "$failed" -eq 0 ]; then
            result_text="Exitoso"
            result_color="good"
          else
            result_text="Fallido"
            result_color="danger"
          fi
          user_commit=$(echo "${{ github.event.head_commit.committer.username }}")
          last_commit_name=$(echo "${{ github.event.head_commit.message }}")
          repo_url=$(echo "${{ github.repositoryUrl }}")
          repo_url=${repo_url//git:/https:}
          event_name=$(echo "${{ github.event_name }}")
          full_text="📊 E2E Resultado *$result_text*: Github workflow *${{github.workflow}}* ejecutado por *$user_commit* en el branch <$repo_url|$branch_name>"
          msg="📊 E2E Results on branch: $last_commit_name $branch_name\n\n• Total: $total\n• Passed: $passed\n• Failed: $failed\n• Pending: $pending\n•Skipped: $skipped"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"channel\":\"e2e-cypress-notifications\",\"text\":\"$full_text\", \"attachments\": [{ \"color\": \"$result_color\", \"author_name\": \"$user_commit\", \"author_link\": \"https://github.com/$user_commit\", \"author_icon\": \"https://github.com/$user_commit.png?size=32\", \"fields\": [{ \"title\": \"Branch\", \"value\": \"$branch_name\", \"short\": true}, { \"title\": \"Event\", \"value\": \"$event_name\", \"short\": true} ] }] }" \
            https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $AUTH_KEY_SLACK"
